# Form implementation generated from reading ui file 'UI_Reply.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReplyDialog(object):
    def setupUi(self, ReplyDialog):
        ReplyDialog.setObjectName("ReplyDialog")
        ReplyDialog.resize(844, 498)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReplyDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=ReplyDialog)
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgba(170, 0, 255, 15);\n"
"border-radius:26px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame)
        self.widget_3.setMinimumSize(QtCore.QSize(820, 474))
        self.widget_3.setMaximumSize(QtCore.QSize(820, 474))
        self.widget_3.setStyleSheet(".QWidget{\n"
"background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                  stop:0 rgb(105, 27, 253), \n"
"                                  stop:1 rgb(200, 160, 240));\n"
"border-radius:12px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(18, 12, 12, 12)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_title = QtWidgets.QLabel(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgba(222, 255, 255, 255)")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_5.addWidget(self.label_title)
        self.mainframe = QtWidgets.QFrame(parent=self.widget_3)
        self.mainframe.setStyleSheet("background:rgba(0, 0, 0, 0);")
        self.mainframe.setObjectName("mainframe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainframe)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 4)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame_12 = QtWidgets.QFrame(parent=self.mainframe)
        self.horizontalFrame_12.setMaximumSize(QtCore.QSize(16777215, 52))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.horizontalFrame_12.setFont(font)
        self.horizontalFrame_12.setStyleSheet("border-radius: 4px;\n"
"background:rgb(255, 255, 255);")
        self.horizontalFrame_12.setObjectName("horizontalFrame_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalFrame_12)
        self.horizontalLayout_17.setContentsMargins(9, 6, 9, 6)
        self.horizontalLayout_17.setSpacing(2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(parent=self.horizontalFrame_12)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.KeyWord_lineEdit = QtWidgets.QLineEdit(parent=self.horizontalFrame_12)
        self.KeyWord_lineEdit.setMinimumSize(QtCore.QSize(116, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.KeyWord_lineEdit.setFont(font)
        self.KeyWord_lineEdit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.KeyWord_lineEdit.setObjectName("KeyWord_lineEdit")
        self.horizontalLayout_17.addWidget(self.KeyWord_lineEdit)
        self.Rule_comboBox = QtWidgets.QComboBox(parent=self.horizontalFrame_12)
        self.Rule_comboBox.setMinimumSize(QtCore.QSize(48, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        self.Rule_comboBox.setFont(font)
        self.Rule_comboBox.setStyleSheet("QComboBox {\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 9px;\n"
"    border: 1px solid rgba(105, 27, 253, 180);\n"
"    padding: 2px 6px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid rgba(105, 27, 253, 180);\n"
"    border-radius: 2px;\n"
"    background: white;\n"
"}")
        self.Rule_comboBox.setIconSize(QtCore.QSize(0, 0))
        self.Rule_comboBox.setObjectName("Rule_comboBox")
        self.Rule_comboBox.addItem("")
        self.Rule_comboBox.addItem("")
        self.Rule_comboBox.addItem("")
        self.horizontalLayout_17.addWidget(self.Rule_comboBox)
        self.label_18 = QtWidgets.QLabel(parent=self.horizontalFrame_12)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.Reply_lineEdit = QtWidgets.QLineEdit(parent=self.horizontalFrame_12)
        self.Reply_lineEdit.setMinimumSize(QtCore.QSize(146, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Reply_lineEdit.setFont(font)
        self.Reply_lineEdit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Reply_lineEdit.setObjectName("Reply_lineEdit")
        self.horizontalLayout_17.addWidget(self.Reply_lineEdit)
        self.emotion_pushButton = QtWidgets.QPushButton(parent=self.horizontalFrame_12)
        self.emotion_pushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.emotion_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.emotion_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/img/page3/page3_回复表情.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.emotion_pushButton.setIcon(icon)
        self.emotion_pushButton.setIconSize(QtCore.QSize(24, 24))
        self.emotion_pushButton.setObjectName("emotion_pushButton")
        self.horizontalLayout_17.addWidget(self.emotion_pushButton)
        self.file_pushButton = QtWidgets.QPushButton(parent=self.horizontalFrame_12)
        self.file_pushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.file_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.file_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/img/page1/page1_打开文件.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.file_pushButton.setIcon(icon1)
        self.file_pushButton.setIconSize(QtCore.QSize(24, 24))
        self.file_pushButton.setObjectName("file_pushButton")
        self.horizontalLayout_17.addWidget(self.file_pushButton)
        self.label_19 = QtWidgets.QLabel(parent=self.horizontalFrame_12)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgba(0, 0, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.Apply_lineEdit = QtWidgets.QLineEdit(parent=self.horizontalFrame_12)
        self.Apply_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.Apply_lineEdit.setFont(font)
        self.Apply_lineEdit.setStyleSheet("color:rgb(0, 0, 0);\n"
"background:rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.Apply_lineEdit.setObjectName("Apply_lineEdit")
        self.horizontalLayout_17.addWidget(self.Apply_lineEdit)
        self.pushButton_load = QtWidgets.QPushButton(parent=self.horizontalFrame_12)
        self.pushButton_load.setMinimumSize(QtCore.QSize(42, 28))
        self.pushButton_load.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_load.setStyleSheet("QPushButton {\n"
"    background-color: rgba(153, 30, 30, 180);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(178, 44, 44, 0.75);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(121, 24, 24, 0.85);\n"
"}")
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_17.addWidget(self.pushButton_load)
        self.pushButton_add = QtWidgets.QPushButton(parent=self.horizontalFrame_12)
        self.pushButton_add.setMinimumSize(QtCore.QSize(42, 28))
        self.pushButton_add.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_add.setStyleSheet("QPushButton {\n"
"    background-color: rgba(105, 27, 253, 180);\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(105, 27, 253, 0.75);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 27, 253, 0.85);\n"
"}")
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_17.addWidget(self.pushButton_add)
        self.verticalLayout_2.addWidget(self.horizontalFrame_12)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.mainframe)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.scrollArea.setStyleSheet("QScrollArea, QScrollArea * {\n"
"    border: none;\n"
"    background: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QScrollArea QScrollBar:vertical {\n"
"    width: 8px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::handle:vertical {\n"
"    background: rgba(255, 255, 255, 20%);\n"
"    border-radius: 4px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::handle:vertical:hover {\n"
"    background: rgba(255, 255, 255, 70%);\n"
"}\n"
"\n"
"QScrollArea QScrollBar::add-line:vertical,\n"
"QScrollArea QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    width: 0px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollArea QScrollBar::add-page:vertical,\n"
"QScrollArea QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"    border-radius: 4px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 774, 287))
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.FieldsStayAtSizeHint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout.setContentsMargins(6, 12, 0, 6)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 6, 6, -1)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(parent=self.mainframe)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(88, 36))
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(88, 36))
        self.pushButton_cancel.setStyleSheet("QPushButton {\n"
"    background-color: rgba(240, 240, 240, 255);\n"
"    color: rgba(105, 27, 253, 220);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 250);\n"
"    color: rgba(105, 27, 253, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 220);\n"
"    color: rgba(105, 27, 253, 255);\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_save = QtWidgets.QPushButton(parent=self.mainframe)
        self.pushButton_save.setMinimumSize(QtCore.QSize(88, 36))
        self.pushButton_save.setMaximumSize(QtCore.QSize(88, 36))
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"    background-color: rgba(105, 27, 253, 180);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(105, 27, 253, 120);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 27, 253, 250);\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.mainframe)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.setStretch(0, 5)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.setStretch(0, 4)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ReplyDialog)
        QtCore.QMetaObject.connectSlotsByName(ReplyDialog)

    def retranslateUi(self, ReplyDialog):
        _translate = QtCore.QCoreApplication.translate
        ReplyDialog.setWindowTitle(_translate("ReplyDialog", "Dialog"))
        self.label_title.setText(_translate("ReplyDialog", "自动回复规则"))
        self.label_17.setText(_translate("ReplyDialog", "关键词"))
        self.KeyWord_lineEdit.setPlaceholderText(_translate("ReplyDialog", "关键词"))
        self.Rule_comboBox.setItemText(0, _translate("ReplyDialog", "包含"))
        self.Rule_comboBox.setItemText(1, _translate("ReplyDialog", "等于"))
        self.Rule_comboBox.setItemText(2, _translate("ReplyDialog", "正则"))
        self.label_18.setText(_translate("ReplyDialog", "回复"))
        self.Reply_lineEdit.setPlaceholderText(_translate("ReplyDialog", "消息或文件"))
        self.label_19.setText(_translate("ReplyDialog", "应用于"))
        self.Apply_lineEdit.setPlaceholderText(_translate("ReplyDialog", "好友/群聊备注"))
        self.pushButton_load.setText(_translate("ReplyDialog", "导入"))
        self.pushButton_add.setText(_translate("ReplyDialog", "添加"))
        self.pushButton_cancel.setText(_translate("ReplyDialog", "取消"))
        self.pushButton_save.setText(_translate("ReplyDialog", "保存"))
